import { defineStore } from 'pinia';

const STORED_LANG_KEY = 'bien_pos_language';

const translations = {
  id: {
    // Navbar
    searchPlaceholder: 'Pencari Pintar',
    promoAndRewards: 'Promo & Hadiah',
    shoppingCart: 'Keranjang Belanja',
    orderNotifications: 'Notifikasi Pesanan',
    storeProfile: 'Profil Toko',
    cashierSettings: 'Pengaturan Kasir',
    logoutShiftClose: 'Keluar / Ganti Shift Kasir',
    switchLanguage: 'Bahasa',
    indonesian: 'Bahasa Indonesia',
    english: 'English',
    
    // Sidebar (Shortened names to prevent dropdown chevron collision)
    dashboard: 'Dasbor',
    cashier: 'Kasir',
    cashInOut: 'Kas Masuk/Keluar',
    productCatalog: 'Katalog',
    productList: 'Daftar Produk',
    specialTypes: 'Tipe Spesial',
    printBarcode: 'Cetak Barcode',
    printLabel: 'Cetak Label',
    inventoryAndStock: 'Inventori',
    stockInOut: 'Stok Masuk/Keluar',
    franchiseDashboard: 'Franchise',
    marketing: 'Marketing',
    customerManagement: 'Pelanggan',
    customerSatisfaction: 'Kepuasan',
    discountsPromos: 'Diskon & Promo',
    supplierList: 'Supplier',
    employees: 'Karyawan',
    attendance: 'Absensi',
    employeePermissions: 'Hak Akses',
    salesCommission: 'Komisi',
    employeeLogs: 'Log Aktivitas',
    employeeSchedule: 'Jadwal Kerja',
    insightsAi: 'Insight AI',
    salesRecommendations: 'Rekomendasi',
    stockPredictive: 'Prediksi Stok',
    performanceAnalytics: 'Analisis',
    reportsBookkeeping: 'Laporan',
    closingReports: 'Laporan Penutupan',
    transactionLogs: 'Log Transaksi',
    profitLossSummary: 'Laba Rugi (P&L)',
    others: 'Lainnya',
    onlineOrder: 'Online Order',
    qrPayment: 'Pembayaran QRIS',
    onlineStoreSettings: 'Toko Online',
    storeFunding: 'Pemodalan',
    storeMonitoring: 'Monitoring',
    systemSettings: 'Pengaturan',

    // Login Page
    loginTitle: 'Masuk ke Aplikasi POS',
    loginSubtitle: 'Pilih Peran dan Masukkan Kata Sandi Anda',
    roleLabel: 'Peran Pekerjaan',
    passwordLabel: 'Kata Sandi',
    loginButton: 'Masuk ke Pos Register',
    loginSuccess: 'Berhasil Masuk!',
    loginSuccessMsg: 'Selamat datang kembali, ',
    secretCredentialsTitle: 'Informasi Kata Sandi (README.md)',
    managerRole: 'Manager (Hak Akses Penuh)',
    staffRole: 'Staff (Hak Akses Terbatas)',
    managerPasswordInfo: 'Password Manager: manager123',
    staffPasswordInfo: 'Password Staff: staff123',

    // Settings & Commission
    commissionRateLabel: 'Persentase Komisi (%)',
    commissionRestrictedWarning: 'Peran Staff tidak dapat mengubah persentase komisi. Kontak Manager untuk mengubahnya.',
    saveSettings: 'Simpan Pengaturan',
    storeProfileTab: 'Profil Toko & Struk',
    dbConnectionTab: 'Koneksi Database MySQL',
    commissionTab: 'Pengaturan Komisi Penjualan',
    managerAccessOnly: 'Khusus Manager',
    storeNameLbl: 'Nama Toko / Resto',
    storeAddressLbl: 'Alamat Toko',
    storePhoneLbl: 'Nomor Telepon',
    receiptFooterLbl: 'Pesan Footer Struk',

    // Dashboard View
    todaySales: 'Penjualan Hari Ini',
    realtimePos: 'Realtime Kasir POS',
    totalTx: 'Total Transaksi',
    ordersCount: 'Pesanan',
    avgPerTx: 'Rata-rata',
    lowStockTitle: 'Stok Hampir Habis',
    itemsCount: 'Item',
    needRestock: 'Perlu Restok Segera',
    newCustomersTitle: 'Pelanggan Baru',
    peopleCount: 'Orang',
    registeredMember: 'Member Terdaftar',
    quickActionsTitle: 'Aksi Cepat Kasir',
    openPosBtn: 'Buka Kasir POS',
    quickCashInOutBtn: 'Kas Masuk / Keluar',
    manageProductsBtn: 'Kelola Katalog Produk',
    viewReportsBtn: 'Lihat Laporan Penjualan',
    salesTrendTitle: 'Grafik Tren Penjualan',
    recentTxTitle: 'Transaksi Terbaru',
    viewAllTx: 'Lihat Semua',
    noRecentTx: 'Belum ada transaksi hari ini',
    txTimeCol: 'Waktu',
    cashierCol: 'Kasir',
    totalCol: 'Total',
    paymentCol: 'Pembayaran',
    actionCol: 'Aksi',

    // Cashier View
    inAwayOption: 'In/Away',
    orderNotes: 'Keterangan',
    emptyCartText: 'Belum ada item di keranjang',
    totalItemsCount: 'Jumlah Item',
    servedBy: 'Dilayani Oleh',
    moreActions: 'Lainnya',
    orderDiscount: 'Disc Pesanan',
    shippingFee: 'Ongkos Kirim',
    voidOrder: 'Void Pesanan',
    paySubmitBtn: 'Bayar',
    subtotalLbl: 'Subtotal',
    allCategories: 'Semua Kategori',
    searchProductPlaceholder: 'Cari nama produk / barcode...',

    // Products View
    addProduct: 'Tambah Produk',
    editProduct: 'Edit Produk',
    adjustStock: 'Ubah Stok',
    deleteProduct: 'Hapus Produk',
    productName: 'Nama Produk',
    photoUrl: 'URL Foto Gambar',
    category: 'Kategori',
    variant: 'Varian',
    skuCode: 'SKU',
    barcode: 'Barcode',
    stockQty: 'Qty Stok',
    unitLbl: 'Satuan',
    costPrice: 'Harga Beli',
    sellPrice: 'Harga Jual (Toko)',
    onlinePrice: 'Harga Online',
    saveChanges: 'Simpan Perubahan',
    cancel: 'Batal',
    confirmDeleteTitle: 'Konfirmasi Hapus',
    confirmDeleteMsg: 'Apakah Anda yakin ingin menghapus produk ini?',
    deleteSuccess: 'Produk berhasil dihapus',
    saveSuccess: 'Produk berhasil disimpan',
    productCatalogTitle: 'Katalog Produk & Harga',
    tabProducts: 'Produk',
    tabCategory: 'Kategori',
    tabPackage: 'Paket',
    tabAddon: 'Addon',
    tabBrand: 'Brand',
    tabSpec: 'Spesifikasi',
    uploadFromDevice: '📁 Upload Foto dari Perangkat',
    orEnterUrl: 'Atau masukkan URL Foto Gambar (https://...)',
    reorderCol: 'Urutan',

    // Inventory View
    inventoryTitle: 'Inventori & Manajemen Stok',
    stockInTab: 'Stok Masuk',
    stockOutTab: 'Stok Keluar',
    productionTab: 'Produksi Stok',
    addStockIn: '+ Tambah Stok Masuk',
    addStockOut: '+ Catat Stok Keluar',
    supplierName: 'Supplier',
    notesLbl: 'Catatan',
    receivedBy: 'Diterima oleh',
    statusLbl: 'Status',
    dateCol: 'Tanggal',
    productCol: 'Produk',
    qtyCol: 'Jumlah',
    typeCol: 'Tipe',
    operatorCol: 'Operator',
    batchNo: 'No Batch',
    productionDate: 'Tgl Produksi',

    // Reports View
    reportsTitle: 'Laporan & Pembukuan',
    salesClosingTab: 'Laporan Penutupan Penjualan',
    pnlTab: 'Ringkasan Laba Rugi (P&L)',
    productSummaryTab: 'Ringkasan Penjualan Produk',
    txLogsTab: 'Logs Transaksi',
    filterDaily: 'Per Tanggal',
    filterMonthly: 'Per Bulan',
    selectDate: 'Pilih Tanggal',
    selectMonth: 'Pilih Bulan',
    printReport: 'Cetak Laporan',
    exportExcel: 'Export Excel',
    totalGrossSales: 'Total Penjualan Kotor',
    totalNetProfit: 'Estimasi Laba Bersih',
    totalDiscountVal: 'Total Diskon Diberikan',
    totalVoidVal: 'Total Void / Dibatalkan',
    salesByCategory: 'Penjualan Berdasarkan Kategori',
    topSellingTitle: 'Produk Terlaris',
    soldQty: 'Terjual',

    // Employees & Attendance View
    employeesTitle: 'Manajemen Karyawan & Hak Akses',
    addEmployee: '+ Tambah Karyawan',
    employeeNameCol: 'Nama Karyawan',
    pinCodeCol: 'PIN Akses',
    roleCol: 'Peran',
    commissionCol: 'Rate Komisi',
    statusCol: 'Status',
    activeStatus: 'Aktif',
    inactiveStatus: 'Nonaktif',
    attendanceTitle: 'Presensi & Absensi Wajah',
    checkInBtn: 'Absen Masuk',
    checkOutBtn: 'Absen Keluar',
    faceCameraHint: 'Posisikan wajah Anda di area kamera untuk pemindaian',

    // Barcode & Label View
    barcodeTitle: 'Cetak Barcode & Label Harga',
    selectProductsToPrint: 'Pilih Produk untuk Dicetak',
    paperSizeLbl: 'Ukuran Kertas',
    printCopiesLbl: 'Jumlah Salinan',
    printPreviewBtn: 'Pratinjau & Cetak',
    tabProductBarcode: 'Cetak Barcode Produk',
    tabShelfPriceLabel: 'Cetak Label Harga Rak',
    shelfFormatLbl: 'Format Label Rak',
    shelfHint: 'Label harga rak siap dipasang di etalase/rak display resto.',
    barcodePreviewCol: 'Preview Barcode',
    size33x15: 'Ukuran 33x15mm (3 Kolom Roll Thermal)',
    size50x20: 'Ukuran 50x20mm (2 Kolom Roll Thermal)',
    sizeA4: 'A4 Sticker (40 Barcode / Lembar Stiker)',
    optStandardShelf: 'Standard Shelf Tag 70x35mm',
    optLargePromo: 'Large Promo Tag 100x50mm',
    notifPrintTitle: 'Cetak Barcode & Label',
    notifPrintMsg: 'Menyiapkan {n} salinan barcode/label...',

    // Cash In Out View
    cashInOutTitle: 'Pencatatan Kas Masuk & Kas Keluar',
    cashInRecordBtn: '+ Kas Masuk',
    cashOutRecordBtn: '- Kas Keluar',
    amountLbl: 'Nominal (Rp)',
    reasonLbl: 'Alasan / Keperluan',
    currentCashBalance: 'Saldo Kasir Saat Ini',

    // Customers View
    customersTitle: 'Manajemen Pelanggan & Poin',
    addCustomerBtn: '+ Tambah Pelanggan',
    customerNameCol: 'Nama Pelanggan',
    phoneCol: 'No Telepon / WA',
    pointsCol: 'Poin Rewards',
    memberTierCol: 'Tingkat Member',

    // Banners View
    bannersTitle: 'Banner Spanduk & Display Resto',
    addBanner: '+ Upload Banner Baru',
    positionLbl: 'Posisi',

    // Marketing View
    marketingTitle: 'Promosi & Voucher Diskon',
    addPromo: '+ Buat Promo Baru',
    voucherCode: 'Kode Voucher',
    promoName: 'Nama Promosi',
    discountVal: 'Nilai Diskon',
    validPeriod: 'Periode Berlaku',

    // Funding View
    fundingTitle: 'Pemodalan Resto & GoTyme Modal Usaha',
    readyLimit: 'Plafon Siap Cair: IDR 50.000.000',
    fundingBannerTitle: 'Pinjaman Pemodalan Tanpa Jaminan untuk Pemilik Resto',
    fundingBannerDesc: 'Bunga rendah 0.99%/bulan, proses persetujuan cepat berdasarkan histori transaksi kasir POS Anda.',
    applyFundingBtn: 'Ajukan Pemodalan Sekarang',
    fundingHistory: 'Riwayat Pengajuan Pemodalan',
    applicationNo: 'No. Pengajuan',
    applicationDate: 'Tanggal Pengajuan',
    loanLimit: 'Plafon Pinjaman',
    tenorMonths: 'Tenor (Bulan)',
    approvalStatus: 'Status Persetujuan',

    // Deposit View
    depositTitle: 'Manajemen Deposit Pelanggan & Tipe Spesial Produk',
    topUpDepositBtn: '+ Top Up Deposit Baru',
    tabCustDeposit: 'Saldo Deposit Pelanggan',
    tabSpecialTypes: 'Tipe Spesial & Modifikator Produk',
    lastUsed: 'Terakhir Digunakan',
    actions: 'Aksi',
    history: 'Riwayat / History',
    manageSpecialTypesHint: 'Kelola varian spesial, topping tambahan, level pedas, dan opsi porsi khusus.',
    addSpecialType: '+ Buat Tipe Spesial',
    modifierName: 'Nama Modifikator',
    variantOptions: 'Pilihan Variasi / Topping',
    extraFee: 'Biaya Tambahan',
    appliedTo: 'Diterapkan Pada',
    topUpModalTitle: 'Top Up Saldo Deposit',
    customer: 'Pelanggan',
    selectCustomer: 'Pilih Pelanggan',
    topUpAmount: 'Nominal Top Up',
    confirmTopUp: 'Konfirmasi Top Up',

    // Online Sales View
    onlineSalesTitle: 'Penjualan Online & Integrasi E-Commerce',
    channelConnected: 'Channel Status: TERHUBUNG',
    webOrderNo: 'No. Pesanan Web',
    channel: 'Channel',
    customerNameHeader: 'Pemesan',
    orderItems: 'Item Pesanan',
    totalAmountCol: 'Total Rp',

    // Online Store Settings View
    onlineStoreSettingsTitle: 'Pengaturan Toko Online & Aplikasi Mobile Resto',
    saveWebSettings: 'Simpan Pengaturan Web',
    tabWebStore: 'Toko Online Web (E-Catalog)',
    tabMobileApp: 'Aplikasi Mobile App (Android & iOS)',
    onlineStoreStatus: 'Status Toko Online',
    activeCanReceiveOrders: 'Aktif (Dapat Menerima Pesanan Web)',
    webDomain: 'Domain Toko Web',
    deliveryMethod: 'Metode Delivery',
    pickUp: 'Ambil di Tempat (Pick Up)',
    storeDelivery: 'Kurir Toko (Delivery)',
    minOrder: 'Minimal Pemesanan (Rp)',
    mobileAppTitle: 'Mobile App Resto Android & iOS',
    mobileAppStatus: 'Status App Store / Play Store: READY & PUBLISHED',
    generateApk: 'Generate APK / Build Mobile',

    // Payment Methods View
    paymentMethodsTitle: 'Pengaturan Olsera & Netzme QRIS Gateway',
    addGatewayBtn: '+ Integrasi Payment Gateway',
    qrisStatusBanner: 'Status Integrasi: AKTIF & TERHUBUNG (Bank Indonesia Standar QRIS)',
    gatewayName: 'Nama Gateway / Pembayaran',
    integrationType: 'Tipe Integrasi',
    merchantId: 'Merchant ID / NMI',
    mdrFee: 'MDR Fee (%)',
    cashierStatus: 'Status Kasir',
    configure: 'Konfigurasi',
    active: 'Aktif',
    inactive: 'Mati',

    // Transactions View
    transactionsTitle: 'Riwayat Transaksi POS',
    all: 'Semua',
    totalFilteredTx: 'Total Transaksi Filter:',
    totalTurnover: 'Total Omzet:',
    txNo: 'No. Transaksi',
    timeCol: 'Waktu',
    orderTypeCol: 'Tipe Pesanan',
    paymentMethodCol: 'Metode Pembayaran',
    reprintReceiptBtn: 'Cetak Struk',

    // Franchise View
    franchiseTitle: 'Dashboard Multi-Cabang & Franchise Monitoring',
    addBranchBtn: '+ Tambah Cabang Franchise',
    totalOutlets: 'Total Cabang Outlet',
    totalMultiBranchSales: 'Total Omzet Multi-Cabang Hari Ini',
    busiestBranch: 'Cabang Teramai',
    branchCode: 'Kode Cabang',
    branchName: 'Nama Outlet Cabang',
    branchManager: 'Manager Cabang',
    city: 'Kota',
    todaySalesCol: 'Penjualan Hari Ini',
    realtimeAction: 'Aksi Realtime',
    liveMonitor: 'Pantau Live',

    // Attendance View
    openFaceCamera: 'Buka Kamera Absensi Wajah (Live Camera Check-In)',
    scanAbsence: 'Scan Absen',
    scanQrMobile: 'Pindai QR Kode HP',
    faceAbsenceModalTitle: 'Absensi Biometric Wajah',
    takeSnapshot: 'Ambil Foto Wajah (Snap)',
    retakePhoto: 'Foto Ulang',
    branchOfficeYogya: 'Kantor Cabang Yogyakarta',
    confirmFaceCheckin: 'Konfirmasi Absensi Masuk',

    // Miscellaneous Views
    depositTitle: 'Deposit & Simpanan Pelanggan',
    paymentMethodsTitle: 'Metode Pembayaran POS',
    insightsTitle: 'Analisis Prediktif & AI Insights',

    // Payment & Receipt Modals
    selectPaymentMethod: 'Pilih Cara Pembayaran',
    exactMoney: 'Uang Pas',
    payActionBtn: 'Bayar',
    keyboardShortcutHint: 'Input keyboard aktif: [0-9] Angka | [Backspace] Hapus | [Enter] Bayar | [Esc] Batal',
    totalPayment: 'Total Pembayaran',
    changeAmount: 'Kembalian',
    sendToKitchen: 'Kirim ke Dapur',
    printCustom: 'Cetak Custom',
    printReceipt: 'Cetak Resi',
    newTransactionBtn: '+ Baru',
    selectProducts: '1. Pilih Produk',
    cartAndPay: '2. Keranjang & Bayar',
    openCart: 'Buka Keranjang →',
    reorderHint: 'Tarik ikon ☰ atau tekan tombol panah untuk mengubah urutan produk.',
    mNavDashboard: 'Dasbor',
    mNavCashier: 'Kasir',
    mNavProducts: 'Produk',
    mNavReports: 'Laporan',
    mNavSettings: 'Setting'
  },
  en: {
    // Navbar
    searchPlaceholder: 'Smart Search',
    promoAndRewards: 'Promos & Rewards',
    shoppingCart: 'Shopping Cart',
    orderNotifications: 'Order Notifications',
    storeProfile: 'Store Profile',
    cashierSettings: 'Cashier Settings',
    logoutShiftClose: 'Logout / Change Cashier Shift',
    switchLanguage: 'Language',
    indonesian: 'Indonesian',
    english: 'English',
    
    // Sidebar (Shortened names to prevent dropdown chevron collision)
    dashboard: 'Dashboard',
    cashier: 'Cashier',
    cashInOut: 'Cash Flow',
    productCatalog: 'Catalog',
    productList: 'Product List',
    specialTypes: 'Special Types',
    printBarcode: 'Print Barcode',
    printLabel: 'Print Label',
    inventoryAndStock: 'Inventory',
    stockInOut: 'Stock In/Out',
    franchiseDashboard: 'Franchise',
    marketing: 'Marketing',
    customerManagement: 'Customers',
    customerSatisfaction: 'Satisfaction',
    discountsPromos: 'Discounts & Promos',
    supplierList: 'Suppliers',
    employees: 'Employees',
    attendance: 'Attendance',
    employeePermissions: 'Permissions',
    salesCommission: 'Commission',
    employeeLogs: 'Activity Logs',
    employeeSchedule: 'Schedule',
    insightsAi: 'Insights AI',
    salesRecommendations: 'Recommendations',
    stockPredictive: 'Stock Prediction',
    performanceAnalytics: 'Analytics',
    reportsBookkeeping: 'Reports',
    closingReports: 'Sales Closing',
    transactionLogs: 'Transaction Logs',
    profitLossSummary: 'Profit & Loss (P&L)',
    others: 'Others',
    onlineOrder: 'Online Order',
    qrPayment: 'QRIS Payment',
    onlineStoreSettings: 'Online Store',
    storeFunding: 'Funding',
    storeMonitoring: 'Monitoring',
    systemSettings: 'Settings',

    // Login Page
    loginTitle: 'Sign In to POS Application',
    loginSubtitle: 'Select Your Role and Enter Password',
    roleLabel: 'Work Role',
    passwordLabel: 'Password',
    loginButton: 'Sign In to POS Register',
    loginSuccess: 'Login Successful!',
    loginSuccessMsg: 'Welcome back, ',
    secretCredentialsTitle: 'Password Info (from README.md)',
    managerRole: 'Manager (Full Access)',
    staffRole: 'Staff (Restricted Access)',
    managerPasswordInfo: 'Manager Password: manager123',
    staffPasswordInfo: 'Staff Password: staff123',

    // Settings & Commission
    commissionRateLabel: 'Commission Percentage (%)',
    commissionRestrictedWarning: 'Staff role cannot modify commission percentage. Contact Manager to update.',
    saveSettings: 'Save Settings',
    storeProfileTab: 'Store & Receipt Profile',
    dbConnectionTab: 'MySQL Database Connection',
    commissionTab: 'Sales Commission Settings',
    managerAccessOnly: 'Manager Access Only',
    storeNameLbl: 'Store / Restaurant Name',
    storeAddressLbl: 'Store Address',
    storePhoneLbl: 'Phone Number',
    receiptFooterLbl: 'Receipt Footer Message',

    // Dashboard View
    todaySales: "Today's Sales",
    realtimePos: 'Realtime POS Cashier',
    totalTx: 'Total Transactions',
    ordersCount: 'Orders',
    avgPerTx: 'Average',
    lowStockTitle: 'Low Stock Alert',
    itemsCount: 'Items',
    needRestock: 'Needs Restock Soon',
    newCustomersTitle: 'New Customers',
    peopleCount: 'Members',
    registeredMember: 'Registered Members',
    quickActionsTitle: 'Cashier Quick Actions',
    openPosBtn: 'Open POS Cashier',
    quickCashInOutBtn: 'Cash In / Out',
    manageProductsBtn: 'Manage Product Catalog',
    viewReportsBtn: 'View Sales Reports',
    salesTrendTitle: 'Sales Trend Chart',
    recentTxTitle: 'Recent Transactions',
    viewAllTx: 'View All',
    noRecentTx: 'No transactions recorded today',
    txTimeCol: 'Time',
    cashierCol: 'Cashier',
    totalCol: 'Total',
    paymentCol: 'Payment',
    actionCol: 'Action',

    // Cashier View
    inAwayOption: 'In/Away',
    orderNotes: 'Notes',
    emptyCartText: 'No items in cart',
    totalItemsCount: 'Total Items',
    servedBy: 'Served By',
    moreActions: 'More',
    orderDiscount: 'Order Discount',
    shippingFee: 'Shipping Fee',
    voidOrder: 'Void Order',
    paySubmitBtn: 'Pay Now',
    subtotalLbl: 'Subtotal',
    allCategories: 'All Categories',
    searchProductPlaceholder: 'Search product name / barcode...',

    // Products View
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    adjustStock: 'Adjust Stock',
    deleteProduct: 'Delete Product',
    productName: 'Product Name',
    photoUrl: 'Photo Image URL',
    category: 'Category',
    variant: 'Variant',
    skuCode: 'SKU',
    barcode: 'Barcode',
    stockQty: 'Stock Qty',
    unitLbl: 'Unit',
    costPrice: 'Cost Price',
    sellPrice: 'Selling Price (Store)',
    onlinePrice: 'Online Price',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    confirmDeleteTitle: 'Confirm Delete',
    confirmDeleteMsg: 'Are you sure you want to delete this product?',
    deleteSuccess: 'Product deleted successfully',
    saveSuccess: 'Product saved successfully',
    productCatalogTitle: 'Product Catalog & Pricing',
    tabProducts: 'Products',
    tabCategory: 'Categories',
    tabPackage: 'Packages',
    tabAddon: 'Addons',
    tabBrand: 'Brands',
    tabSpec: 'Specifications',
    uploadFromDevice: '📁 Upload Photo from Device',
    orEnterUrl: 'Or enter Photo Image URL (https://...)',
    reorderCol: 'Order',

    // Inventory View
    inventoryTitle: 'Inventory & Stock Management',
    stockInTab: 'Stock In',
    stockOutTab: 'Stock Out',
    productionTab: 'Stock Production',
    addStockIn: '+ Add Stock In',
    addStockOut: '+ Record Stock Out',
    supplierName: 'Supplier',
    notesLbl: 'Notes',
    receivedBy: 'Received By',
    statusLbl: 'Status',
    dateCol: 'Date',
    productCol: 'Product',
    qtyCol: 'Quantity',
    typeCol: 'Type',
    operatorCol: 'Operator',
    batchNo: 'Batch No',
    productionDate: 'Production Date',

    // Reports View
    reportsTitle: 'Reports & Bookkeeping',
    salesClosingTab: 'Sales Closing Report',
    pnlTab: 'Profit & Loss (P&L) Summary',
    productSummaryTab: 'Product Sales Summary',
    txLogsTab: 'Transaction Logs',
    filterDaily: 'By Date',
    filterMonthly: 'By Month',
    selectDate: 'Select Date',
    selectMonth: 'Select Month',
    printReport: 'Print Report',
    exportExcel: 'Export Excel',
    totalGrossSales: 'Total Gross Sales',
    totalNetProfit: 'Estimated Net Profit',
    totalDiscountVal: 'Total Discount Given',
    totalVoidVal: 'Total Void / Cancelled',
    salesByCategory: 'Sales by Category',
    topSellingTitle: 'Top Selling Products',
    soldQty: 'Sold',

    // Employees & Attendance View
    employeesTitle: 'Employee Management & Permissions',
    addEmployee: '+ Add Employee',
    employeeNameCol: 'Employee Name',
    pinCodeCol: 'Access PIN',
    roleCol: 'Role',
    commissionCol: 'Commission Rate',
    statusCol: 'Status',
    activeStatus: 'Active',
    inactiveStatus: 'Inactive',
    attendanceTitle: 'Attendance & Face Check-in',
    checkInBtn: 'Check In',
    checkOutBtn: 'Check Out',
    faceCameraHint: 'Position your face in front of camera to scan',

    // Barcode & Label View
    barcodeTitle: 'Print Barcode & Price Labels',
    selectProductsToPrint: 'Select Products to Print',
    paperSizeLbl: 'Paper Size',
    printCopiesLbl: 'Print Copies',
    printPreviewBtn: 'Preview & Print',
    tabProductBarcode: 'Print Product Barcode',
    tabShelfPriceLabel: 'Print Shelf Price Labels',
    shelfFormatLbl: 'Shelf Label Format',
    shelfHint: 'Shelf price tags ready for restaurant display shelves.',
    barcodePreviewCol: 'Barcode Preview',
    size33x15: '33x15mm Size (3 Column Thermal Roll)',
    size50x20: '50x20mm Size (2 Column Thermal Roll)',
    sizeA4: 'A4 Sticker (40 Barcode / Sheet)',
    optStandardShelf: 'Standard Shelf Tag 70x35mm',
    optLargePromo: 'Large Promo Tag 100x50mm',
    notifPrintTitle: 'Print Barcode & Labels',
    notifPrintMsg: 'Preparing {n} barcode/label copies...',

    // Cash In Out View
    cashInOutTitle: 'Record Cash In & Cash Out',
    cashInRecordBtn: '+ Cash In',
    cashOutRecordBtn: '- Cash Out',
    amountLbl: 'Amount (Rp)',
    reasonLbl: 'Reason / Purpose',
    currentCashBalance: 'Current Cash Balance',

    // Customers View
    customersTitle: 'Customer Management & Loyalty Points',
    addCustomerBtn: '+ Add Customer',
    customerNameCol: 'Customer Name',
    phoneCol: 'Phone / WhatsApp',
    pointsCol: 'Reward Points',
    memberTierCol: 'Member Tier',

    // Banners View
    bannersTitle: 'Promotional Banners & Display',
    addBanner: '+ Upload New Banner',
    positionLbl: 'Position',

    // Marketing View
    marketingTitle: 'Promotions & Discount Vouchers',
    addPromo: '+ Create New Promo',
    voucherCode: 'Voucher Code',
    promoName: 'Promo Name',
    discountVal: 'Discount Value',
    validPeriod: 'Validity Period',

    // Funding View
    fundingTitle: 'Restaurant Funding & GoTyme Capital',
    readyLimit: 'Available Credit Limit: IDR 50,000,000',
    fundingBannerTitle: 'Unsecured Business Financing for Restaurant Owners',
    fundingBannerDesc: 'Low interest 0.99%/month, instant approval based on your POS cashier transaction history.',
    applyFundingBtn: 'Apply for Funding Now',
    fundingHistory: 'Funding Application History',
    applicationNo: 'Application No.',
    applicationDate: 'Application Date',
    loanLimit: 'Loan Limit',
    tenorMonths: 'Tenor (Months)',
    approvalStatus: 'Approval Status',

    // Deposit View
    depositTitle: 'Customer Deposit Management & Special Product Types',
    topUpDepositBtn: '+ Top Up New Deposit',
    tabCustDeposit: 'Customer Deposit Balance',
    tabSpecialTypes: 'Special Types & Product Modifiers',
    lastUsed: 'Last Used',
    actions: 'Actions',
    history: 'History',
    manageSpecialTypesHint: 'Manage special variants, extra toppings, spice levels, and custom portion options.',
    addSpecialType: '+ Create Special Type',
    modifierName: 'Modifier Name',
    variantOptions: 'Variant / Topping Options',
    extraFee: 'Extra Fee',
    appliedTo: 'Applied To',
    topUpModalTitle: 'Top Up Deposit Balance',
    customer: 'Customer',
    selectCustomer: 'Select Customer',
    topUpAmount: 'Top Up Amount',
    confirmTopUp: 'Confirm Top Up',

    // Online Sales View
    onlineSalesTitle: 'Online Sales & E-Commerce Integration',
    channelConnected: 'Channel Status: CONNECTED',
    webOrderNo: 'Web Order No.',
    channel: 'Channel',
    customerNameHeader: 'Customer Name',
    orderItems: 'Order Items',
    totalAmountCol: 'Total Amount',

    // Online Store Settings View
    onlineStoreSettingsTitle: 'Online Store & Mobile App Settings',
    saveWebSettings: 'Save Web Settings',
    tabWebStore: 'Web Online Store (E-Catalog)',
    tabMobileApp: 'Mobile App (Android & iOS)',
    onlineStoreStatus: 'Online Store Status',
    activeCanReceiveOrders: 'Active (Can Receive Web Orders)',
    webDomain: 'Web Store Domain',
    deliveryMethod: 'Delivery Method',
    pickUp: 'Self Pick Up',
    storeDelivery: 'Store Courier Delivery',
    minOrder: 'Minimum Order (Rp)',
    mobileAppTitle: 'Restaurant Mobile App Android & iOS',
    mobileAppStatus: 'App Store / Play Store Status: READY & PUBLISHED',
    generateApk: 'Generate APK / Build Mobile',

    // Payment Methods View
    paymentMethodsTitle: 'Olsera & Netzme QRIS Gateway Settings',
    addGatewayBtn: '+ Integrate Payment Gateway',
    qrisStatusBanner: 'Integration Status: ACTIVE & CONNECTED (Bank Indonesia QRIS Standard)',
    gatewayName: 'Gateway / Payment Name',
    integrationType: 'Integration Type',
    merchantId: 'Merchant ID / NMI',
    mdrFee: 'MDR Fee (%)',
    cashierStatus: 'Cashier Status',
    configure: 'Configure',
    active: 'Active',
    inactive: 'Inactive',

    // Transactions View
    transactionsTitle: 'POS Transaction History',
    all: 'All',
    totalFilteredTx: 'Total Filtered Transactions:',
    totalTurnover: 'Total Turnover:',
    txNo: 'Transaction No.',
    timeCol: 'Time',
    orderTypeCol: 'Order Type',
    paymentMethodCol: 'Payment Method',
    reprintReceiptBtn: 'Print Receipt',

    // Franchise View
    franchiseTitle: 'Multi-Branch Dashboard & Franchise Monitoring',
    addBranchBtn: '+ Add Franchise Branch',
    totalOutlets: 'Total Outlet Branches',
    totalMultiBranchSales: 'Total Multi-Branch Turnover Today',
    busiestBranch: 'Busiest Branch',
    branchCode: 'Branch Code',
    branchName: 'Branch Outlet Name',
    branchManager: 'Branch Manager',
    city: 'City',
    todaySalesCol: "Today's Sales",
    realtimeAction: 'Realtime Action',
    liveMonitor: 'Live Stream Monitor',

    // Attendance View
    openFaceCamera: 'Open Face Attendance Camera (Live Check-In)',
    scanAbsence: 'Scan Check-In',
    scanQrMobile: 'Scan Mobile Phone QR Code',
    faceAbsenceModalTitle: 'Biometric Face Attendance',
    takeSnapshot: 'Take Face Photo (Snap)',
    retakePhoto: 'Retake Photo',
    branchOfficeYogya: 'Yogyakarta Branch Office',
    confirmFaceCheckin: 'Confirm Attendance Check-In',

    // Miscellaneous Views
    depositTitle: 'Customer Deposits & Balances',
    paymentMethodsTitle: 'POS Payment Methods',
    insightsTitle: 'Predictive Analytics & AI Insights',

    // Payment & Receipt Modals
    selectPaymentMethod: 'Select Payment Method',
    exactMoney: 'Exact Amount',
    payActionBtn: 'Pay',
    keyboardShortcutHint: 'Active keyboard input: [0-9] Numbers | [Backspace] Clear | [Enter] Submit | [Esc] Cancel',
    totalPayment: 'Total Payment',
    changeAmount: 'Change Amount',
    sendToKitchen: 'Send to Kitchen',
    printCustom: 'Custom Print',
    printReceipt: 'Print Receipt',
    newTransactionBtn: '+ New Order',
    selectProducts: '1. Select Products',
    cartAndPay: '2. Cart & Pay',
    openCart: 'View Cart →',
    reorderHint: 'Drag ☰ icon or click arrow buttons to reorder products.',
    mNavDashboard: 'Dashboard',
    mNavCashier: 'Cashier',
    mNavProducts: 'Products',
    mNavReports: 'Reports',
    mNavSettings: 'Settings'
  }
};

export const useLangStore = defineStore('lang', {
  state: () => ({
    currentLang: localStorage.getItem(STORED_LANG_KEY) || 'id'
  }),

  getters: {
    t: (state) => (key) => {
      const dict = translations[state.currentLang] || translations.id;
      return dict[key] || key;
    }
  },

  actions: {
    setLanguage(lang) {
      if (['id', 'en'].includes(lang)) {
        this.currentLang = lang;
        localStorage.setItem(STORED_LANG_KEY, lang);
      }
    }
  }
});
